/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DDL;

import UI.MainMenu;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class ModifyDeleteTable extends javax.swing.JFrame {

    /**
     * Creates new form ModifyDeleteTable
     */
    public ModifyDeleteTable() {
        initComponents();
        tableInCombo();
    }
    
    private void displaydata()
    {
        try 
        {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb","root", "root");
            String q = "describe "+cboTable.getSelectedItem()+"";
            PreparedStatement pstmt = con.prepareStatement(q);
            ResultSet rs = pstmt.executeQuery();
            tbldata.setModel(DbUtils.resultSetToTableModel(rs));
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    private void tableInCombo()
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
            DatabaseMetaData dbmd = con.getMetaData();
            String[] type = {"TABLE"};
            ResultSet rs = dbmd.getTables("tvrepairdb", null,"%", type);
            cboTable.removeAllItems();
            cboTable.addItem("Select");
            while(rs.next())
            {
                String tableName = rs.getString("TABLE_NAME");
                if(!tableName.equalsIgnoreCase("customer") &&
               !tableName.equalsIgnoreCase("tvproductsandservices") &&
               !tableName.equalsIgnoreCase("userlogin"))    // not to show the built-in tables in the combo selection
                {
                    cboTable.addItem(tableName);
                }  
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboTable = new javax.swing.JComboBox<>();
        btndone = new javax.swing.JButton();
        btndrop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        cboType = new javax.swing.JComboBox<>();
        chk1 = new javax.swing.JCheckBox();
        chkp1 = new javax.swing.JCheckBox();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnBACK = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFICATION AND DELETE");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("TABLE MODIFICATION AND DELETION");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Choose table name: ");

        cboTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboTable.setForeground(new java.awt.Color(153, 0, 0));
        cboTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        btndone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndone.setForeground(new java.awt.Color(153, 0, 0));
        btndone.setText("DONE");
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        btndrop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndrop.setForeground(new java.awt.Color(153, 0, 0));
        btndrop.setText("DROP");
        btndrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndropActionPerformed(evt);
            }
        });

        tbldata.setBackground(new java.awt.Color(153, 0, 0));
        tbldata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbldata.setForeground(new java.awt.Color(255, 255, 255));
        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldata);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Column");

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(153, 0, 0));

        cboType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboType.setForeground(new java.awt.Color(153, 0, 0));
        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "int", "float", "double", "varchar(5)", "varchar(10)", "varchar(15)", "varchar(20)", "char" }));
        cboType.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        chk1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chk1.setForeground(new java.awt.Color(153, 0, 0));
        chk1.setText("NULL");
        chk1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        chkp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkp1.setForeground(new java.awt.Color(153, 0, 0));
        chkp1.setText("PRIMARY KEY");
        chkp1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(153, 0, 0));
        btnadd.setText("ADD COLUMN");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(153, 0, 0));
        btnedit.setText("EDIT COLUMN");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(153, 0, 0));
        btndelete.setText("DELETE COLUMN");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(chk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkp1)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkp1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        btnBACK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBACK.setForeground(new java.awt.Color(153, 0, 0));
        btnBACK.setText("BACK TO MAIN MENU");
        btnBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(153, 0, 0));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBACK)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(28, 28, 28))
                                .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btndrop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboTable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear)
                        .addGap(18, 18, 18)
                        .addComponent(btndrop)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKActionPerformed
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBACKActionPerformed

    private void btndropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndropActionPerformed
        // TODO add your handling code here:
        if(cboTable.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(this, "Please select a table name!");
        }
        else
        {
            int choice = JOptionPane.showConfirmDialog(this, 
               "Are you sure you want to delete this table: " +cboTable.getSelectedItem()+"?",
               "Confirm Delete",JOptionPane.YES_NO_OPTION);
            
            if(choice == JOptionPane.YES_OPTION)
            {
                try
                {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
                    String sql = "drop table "+cboTable.getSelectedItem()+"";
                    PreparedStatement pstmt = con.prepareStatement(sql);
                    pstmt.execute();
                    JOptionPane.showMessageDialog(this, cboTable.getSelectedItem()+"Table is deleted.");
                    cboTable.removeAllItems();
                    cboTable.addItem("Select");
                    tableInCombo();

                }catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Delete cancelled.");
            }
        }
        
        
    }//GEN-LAST:event_btndropActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        // TODO add your handling code here:
        if(cboTable.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(this, "Please select a table!");
        }
        else
        {
            displaydata();
        }
    }//GEN-LAST:event_btndoneActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String cName =txtname.getText();
        String dType = cboType.getSelectedItem().toString();
        String st;
        String pKey;
        if(chk1.isSelected())
        {
            st = "NULL";
        }
        else
        {
            st = "NOT NULL";
        }
        if(chkp1.isSelected())
        {
            pKey = "PRIMARY KEY";
        }
        else
        {
            pKey = "";
        }
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
            String q = "alter table "+cboTable.getSelectedItem()+" add "+cName+" "+dType+" "+st+" "+pKey+"";
            PreparedStatement pstmt = con.prepareStatement(q);
            pstmt.execute();
            JOptionPane.showMessageDialog(this,"'"+cName +"' is added to the table");
            displaydata();
            txtname.setText("");
            cboType.setSelectedItem("");
            chk1.setSelected(false);
            chkp1.setSelected(false);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel m = (DefaultTableModel) tbldata.getModel();
        int index = tbldata.getSelectedRow();
        txtname.setText(m.getValueAt(index,0).toString());
        cboType.setSelectedItem(m.getValueAt(index, 1));
        String st = m.getValueAt(index, 2).toString();
        if(st.equals("YES"))
        {
            chk1.setSelected(true);
        }
        else
        {
            chk1.setSelected(false);
        }
        String pKey = m.getValueAt(index, 3).toString();
        if(pKey.equals("PRI"))
        {
            chkp1.setSelected(true);
        }
        else
        {
            chkp1.setSelected(false);
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
         int index = tbldata.getSelectedRow();
         String oldName = tbldata.getValueAt(index, 0).toString();
         String cName = txtname.getText();
         String dType = cboType.getSelectedItem().toString();
         try
         {
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
             String q = "alter table "+cboTable.getSelectedItem()+" change "+oldName+" "+cName+" "+dType+" ";
             PreparedStatement pstmt = con.prepareStatement(q);
             pstmt.execute();
             JOptionPane.showMessageDialog(this,"Column is edited.");
             displaydata();
         }catch(Exception ex)
         {
             JOptionPane.showMessageDialog(this, ex);
         }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int index = tbldata.getSelectedRow();
        String del_cName = tbldata.getValueAt(index, 0).toString();
        
        int choice = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete the column: '" + del_cName + "' ?",
                    "Confirm Delete.",
                    JOptionPane.YES_NO_OPTION);
        
        if(choice==JOptionPane.YES_OPTION)
        {
            try
            {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
                String q = "alter table "+cboTable.getSelectedItem()+" drop column "+del_cName+ "";
                PreparedStatement pstmt = con.prepareStatement(q);
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"Column is deleted.");
                displaydata();
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Delete cancelled.");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        cboTable.setSelectedIndex(0);
        txtname.setText("");
        cboType.setSelectedIndex(0);
        chk1.setSelected(false);
        chkp1.setSelected(false);
        DefaultTableModel md = (DefaultTableModel) tbldata.getModel();
        md.setRowCount(0);
        
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyDeleteTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACK;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btndrop;
    private javax.swing.JButton btnedit;
    private javax.swing.JComboBox<String> cboTable;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chkp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
