/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DML;
import UI.MainMenu;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class InsertUpdateDelete extends javax.swing.JFrame {

    /**
     * Creates new form InsertUpdateDelete
     */
    public InsertUpdateDelete() {
        initComponents();
        tableInCombo();
    }
    private void displaytabledata()
    {
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb","root", "root");
            String q = "select * from "+cboTable.getSelectedItem()+"";
            PreparedStatement pstmt = con.prepareStatement(q);
            ResultSet rs = pstmt.executeQuery();
            tbldata.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex);
        }
    }
    private void tableInCombo()
    {
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb", "root","root");
            DatabaseMetaData dbmd = con.getMetaData();
            String[] type = {"TABLE"};
            ResultSet rs = dbmd.getTables("tvrepairdb", null,"%", type);
            
            while(rs.next())
            {
                cboTable.addItem(rs.getString("TABLE_NAME"));
            }
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboTable = new javax.swing.JComboBox<>();
        btndone = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        btnnewrow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBACK = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANAGE DATA");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("DATA MANAGEMENT");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Choose table name: ");

        cboTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboTable.setForeground(new java.awt.Color(153, 0, 0));
        cboTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        btndone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndone.setForeground(new java.awt.Color(153, 0, 0));
        btndone.setText("DONE");
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btninsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btninsert.setForeground(new java.awt.Color(153, 0, 0));
        btninsert.setText("INSERT");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(153, 0, 0));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(153, 0, 0));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tbldata.setBackground(new java.awt.Color(153, 0, 0));
        tbldata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbldata.setForeground(new java.awt.Color(255, 255, 255));
        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbldata);

        btnnewrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnewrow.setForeground(new java.awt.Color(153, 0, 0));
        btnnewrow.setText("ADD NEW ROW");
        btnnewrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewrowActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("ADD A NEW ROW TO INSERT DATA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnnewrow)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnewrow)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btninsert)
                    .addComponent(btndelete))
                .addGap(58, 58, 58))
        );

        btnBACK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBACK.setForeground(new java.awt.Color(153, 0, 0));
        btnBACK.setText("BACK TO MAIN MENU");
        btnBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(153, 0, 0));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBACK))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboTable, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(btndone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cboTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndone)
                .addGap(18, 18, 18)
                .addComponent(btnclear)
                .addGap(211, 211, 211)
                .addComponent(btnBACK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKActionPerformed
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBACKActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        cboTable.setSelectedIndex(0);
        DefaultTableModel md = (DefaultTableModel) tbldata.getModel();
        md.setRowCount(0);
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb","root","root");
            Statement stmt = con.createStatement();
            String tableName = cboTable.getSelectedItem().toString();
            DefaultTableModel m = (DefaultTableModel) tbldata.getModel();
            int rowIndex = tbldata.getSelectedRow(); //Get the index of the row the user selected
            if(rowIndex == -1)  //If no row is selected (index = -1)
            {
                JOptionPane.showMessageDialog(this, "Please select a row to insert.");
                return;
            }
            if (tbldata.isEditing())
            {
                tbldata.getCellEditor().stopCellEditing(); //to save latest typed values into the model
            }
            String q = "insert into " + tableName + " values (";    //insert query with for loop 
            for (int i = 0; i < m.getColumnCount(); i++)
            {
                Object value = m.getValueAt(rowIndex, i);
                q += "'" + value + "'";
                if (i < m.getColumnCount() - 1) 
                {
                    q += ",";
                }
            }
            q += ")";
            stmt.execute(q);
            JOptionPane.showMessageDialog(this, "New data inserted successfully into '" + tableName+"'.");
            displaytabledata(); 
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error inserting row: " + ex.getMessage());
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        // TODO add your handling code here:
        if(cboTable.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(this, "Please select a table!");
        }
        else
        {
            displaytabledata();
        }
    }//GEN-LAST:event_btndoneActionPerformed

    private void btnnewrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewrowActionPerformed
        // TODO add your handling code here:
        try
        {
            DefaultTableModel m = (DefaultTableModel) tbldata.getModel();
            int columnCount = m.getColumnCount();
            Object[] emptyRow = new Object[columnCount];
            m.addRow(emptyRow);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnnewrowActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb","root","root");
            Statement stmt = con.createStatement();
            String tableName = cboTable.getSelectedItem().toString();
            DefaultTableModel m = (DefaultTableModel) tbldata.getModel();
            int rowIndex = tbldata.getSelectedRow();
            if(rowIndex == -1)
            {
                JOptionPane.showMessageDialog(this, "Please select a row to update.");
                return;
            }
            if (tbldata.isEditing())
            {
                tbldata.getCellEditor().stopCellEditing();
            }
            String q = "update " + tableName + " set ";
            for (int i = 1; i < m.getColumnCount(); i++)
            {
                Object value = m.getValueAt(rowIndex, i);
                String colName = m.getColumnName(i);
                q += colName + "='" + value + "'";
                if (i < m.getColumnCount() - 1)
                {
                    q += ",";
                }
            }
            Object pkValue = m.getValueAt(rowIndex, 0);
            String pkColumn = m.getColumnName(0);
            q += " where " + pkColumn + "='" + pkValue + "'";
            stmt.execute(q);
            JOptionPane.showMessageDialog(this, "Data updated successfully in '" + tableName + "'.");
            displaytabledata();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tvrepairdb","root","root");
            Statement stmt = con.createStatement();
            String tableName = cboTable.getSelectedItem().toString();
            DefaultTableModel m = (DefaultTableModel) tbldata.getModel();
            int rowIndex = tbldata.getSelectedRow();
            
            if(rowIndex == -1)
            {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.");
                return;
            }
            
            String pkColumn = m.getColumnName(0);
            Object pkValue = m.getValueAt(rowIndex, 0);
            int choice = JOptionPane.showConfirmDialog(this, 
                        "Are you sure you want to delete this row : '" + pkColumn + " = " + pkValue + "' ?",
                        "Confirm Delete", JOptionPane.YES_NO_OPTION);
            if(choice == JOptionPane.YES_OPTION)
            {
                String q = "DELETE FROM " + tableName + " WHERE " + pkColumn + "='" + pkValue + "'";
                stmt.execute(q);
                JOptionPane.showMessageDialog(this, "Data deleted successfully from '" + tableName + "'.");
                displaytabledata();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Delete cancelled.");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        displaytabledata();
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertUpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBACK;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndone;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnnewrow;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cboTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldata;
    // End of variables declaration//GEN-END:variables
}
